server:
  port: 8761

spring:
  security:
    user:
      name: ${EUREKA_USER:user}
      password: ${EUREKA_PASSWORD:password}

eureka:
  instance:
    hostname: ${EUREKA_SERVER:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
