server:
  port: 8761
  servlet:
    context-path: /
  ssl:
    key-store: file:${KEYSTORE_FILE:}
    key-store-password: ${KEYSTORE_PASSWORD:}
    enabled: ${SSL_ENABLED:false}

spring:
  security:
    user:
      name: ${EUREKA_USER:user}
      password: ${EUREKA_PASSWORD:password}

management:
  endpoints:
    web:
     base-path: /actuator
     exposure:
       include: info,health,metrics,prometheus

eureka:
  instance:
    hostname: ${EUREKA_SERVER:localhost}
    metadata-map:
      metrics.path: /actuator/prometheus
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
