errorPath: /error

server:
  port: 8082
  servlet:
    context-path: /
  error:
    path: errorPath
  ssl:
    key-store: file:${KEYSTORE_FILE:}
    key-store-password: ${KEYSTORE_PASSWORD:}
    enabled: ${SSL_ENABLED:false}

spring:
  application:
    name: tasks-executor
  profiles:
    active: Logging
  batch:
    job:
      enabled: false
  security:
    user:
      name: ${APP_USER:user}
      password: ${APP_PASSWORD:password}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/tasks}
    username: ${DATASOURCE_USERNAME:japp}
    password: ${DATASOURCE_PASSWORD:secret}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
#      ddl-auto: create
        jdbc:
          time_zone: UTC
        id:
          new_generator_mappings: false
  liquibase:
    user: ${DATASOURCE_ADMIN_USERNAME:jadmin}
    password: ${DATASOURCE_ADMIN_PASSWORD:moresecret}
    change-log: classpath:changelog/db.changelog.sql
  activemq:
    in-memory: false
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER:artemis}
    password: ${BROKER_PASSWORD:artemis}
    pool:
      enabled: true
      max-connections: 10
    ssl:
      keyStorePath: ${KEYSTORE_FILE}
      keyStorePass: ${KEYSTORE_PASSWORD}
      trustStorePath: ${TRUSTSTORE_FILE}
      trustStorePass: ${TRUSTSTORE_PASSWORD}

activemq:
  queue:
    request: QUEUE_REQUEST
    response: QUEUE_RESPONSE

management:
  endpoints:
    enabled-by-default: false
    web:
     base-path: /actuator
     exposure:
       include: info,health,jolokia
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    jolokia:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://user:password@localhost:8761/eureka}
  instance:
    preferIpAddress: true
