version: '3'
services:

  tasks-mongodb:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    volumes:
      - tasks-mongodb-data:/data/db

  tasks-mongoclient:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL="mongodb://root:secret@tasks-mongodb:27017"
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - "8085:8081"
    depends_on:
      - tasks-mongodb

  tasks-activemq:
    image: artemis-debian
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
      EXTRA_ARGS: "--http-host tasks-activemq --relax-jolokia"
    ports:
      - "61616:61616"
      - "8161:8161"

  tasks-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - tasks-mysql-data:/var/lib/mysql
      - "../config/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  tasks-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      - PMA_HOST=tasks-mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"
    depends_on:
      - tasks-mysql

  tasks-eureka:
    image: francescofiora-task-eureka
    environment:
      - "EUREKA_SERVER=tasks-eureka"
    ports:
      - "8761:8761"

  tasks-api:
    image: francescofiora-task-api
    environment:
      - "SPRING_PROFILES_ACTIVE=Logging"
      - "MONGODB_URI=mongodb://root:secret@tasks-mongodb:27017"
      - "BROKER_URL=tcp://tasks-activemq:61616"
      - "EUREKA_URI=http://user:password@tasks-eureka:8761/eureka"
    ports:
      - '8081:8081'
    depends_on:
      - tasks-mongodb
      - tasks-activemq
      - tasks-eureka

  task-executor:
    image: francescofiora-task-executor
    environment:
      - "DATASOURCE_URL=jdbc:mysql://tasks-mysql:3306/tasks"
      - "BROKER_URL=tcp://tasks-activemq:61616"
      - "EUREKA_URI=http://user:password@tasks-eureka:8761/eureka"
    ports:
      - '8082:8082'
    depends_on:
      - tasks-mysql
      - tasks-activemq
      - tasks-eureka

volumes:
  tasks-mysql-data:
  tasks-mongodb-data:
