version: '3'
services:

  tasks-mongodb:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    command:
      - '--config'
      - '/etc/mongo.conf'
      - '--bind_ip_all'
    ports:
      - '27017:27017'
    volumes:
      - tasks-mongodb-data:/data/db
      - "./mongodb/mongo.conf:/etc/mongo.conf"
      - "./certs:/etc/ssl"

  tasks-activemq:
    image: artemis-debian
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
      EXTRA_ARGS: "--http-host tasks-activemq --relax-jolokia"
    volumes:
      - "./artemis-instance:/var/lib/artemis-instance"
    ports:
      - "61616:61616"
      - "8161:8161"

  tasks-mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - tasks-mysql-data:/var/lib/mysql
      - "./mysql/conf.d:/etc/mysql/conf.d/"
      - "./certs:/etc/certs"
      - "./mysql/data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
   
  tasks-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    environment:
      - PMA_HOST=tasks-mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    volumes:
      - "./certs:/etc/certs"
      - "./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    ports:
      - "8080:80"

  tasks-api:
    image: openjdk:8u282-jdk-slim
    environment:
      - "SPRING_PROFILES_ACTIVE=sit"
    volumes:
      - "./tasks-api:/workspace"
    working_dir: /workspace
    command: java -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar ./task-api-1.0-SNAPSHOT.jar
    ports:
      - '8081:8081'
    depends_on:
      - tasks-mongodb
      - tasks-activemq

  task-executor:
    image: openjdk:8u282-jdk-slim
    environment:
      - "SPRING_PROFILES_ACTIVE=sit"
    volumes:
      - "./tasks-executor:/workspace"
    working_dir: /workspace
    command: java -Dcom.sun.management.jmxremote.port=9998 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar ./task-executor-1.0-SNAPSHOT.jar
    ports:
      - '8082:8082'
    depends_on:
      - tasks-mysql
      - tasks-activemq

volumes:
  tasks-mysql-data:
  tasks-mongodb-data:
