version: '3'
services:

  tasks-mongodb:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    command:
      - '--config'
      - '/etc/mongo.conf'
      - '--bind_ip_all'
    ports:
      - '27017:27017'
    volumes:
      - tasks-mongodb-data:/data/db
      - "./mongodb/mongo.conf:/etc/mongo.conf"
      - "./certs:/etc/ssl"

  tasks-activemq:
    image: artemis-debian
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
      EXTRA_ARGS: "--http-host tasks-activemq --relax-jolokia"
    volumes:
      - "./artemis-instance:/var/lib/artemis-instance"
    ports:
      - "61616:61616"
      - "8161:8161"

  tasks-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - tasks-mysql-data:/var/lib/mysql
      - "./mysql/conf.d:/etc/mysql/conf.d/"
      - "./certs:/etc/certs"
      - "./mysql/data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  tasks-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      - PMA_HOST=tasks-mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    volumes:
      - "./certs:/etc/certs"
      - "./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    ports:
      - "8080:80"

  tasks-api:
    image: francescofiora-task-api
    environment:
      - "SPRING_PROFILES_ACTIVE=MongoSsl,AmqSsl,Logging"
      - "SSL_ENABLED=true"
      - "KEYSTORE_PASSWORD=mypass"
      - "KEYSTORE_FILE=/workspace/config/tasks-api-keystore.jks"
      - "TRUSTSTORE_PASSWORD=mypass"
      - "TRUSTSTORE_FILE=/workspace/config/truststore.ts"
      - "MONGODB_URI=mongodb://root:secret@tasks-mongodb:27017/?ssl=true"
      - "BROKER_URL=ssl://tasks-activemq:61616"
      - "BROKER_USER=tasksapi"
    volumes:
      - "./tasks-api:/workspace"
    ports:
      - '8081:8081'
    depends_on:
      - tasks-mongodb
      - tasks-activemq

  task-executor:
    image: francescofiora-task-executor
    environment:
      - "SPRING_PROFILES_ACTIVE=AmqSsl,Logging"
      - "SSL_ENABLED=true"
      - "KEYSTORE_PASSWORD=mypass"
      - "KEYSTORE_FILE=/workspace/config/tasks-executor-keystore.jks"
      - "TRUSTSTORE_PASSWORD=mypass"
      - "TRUSTSTORE_FILE=/workspace/config/truststore.ts"
      - "DATASOURCE_URL=jdbc:mysql://tasks-mysql:3306/tasks?verifyServerCertificate=true&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:./config/tasks-executor-keystore.jks&clientCertificateKeyStorePassword=mypass&trustCertificateKeyStoreUrl=file:./config/truststore.ts&trustCertificateKeyStorePassword=mypass"
      - "BROKER_URL=ssl://tasks-activemq:61616"
      - "BROKER_USER=tasksexecutor"
    volumes:
      - "./tasks-executor:/workspace"
    ports:
      - '8082:8082'
    depends_on:
      - tasks-mysql
      - tasks-activemq

volumes:
  tasks-mysql-data:
  tasks-mongodb-data:
