version: '3'
services:

  tasks-mongodb:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    volumes:
      - tasks-mongodb-data:/data/db

  tasks-activemq:
    image: artemis-debian
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
      EXTRA_ARGS: "--http-host tasks-activemq --relax-jolokia"
    ports:
      - "61616:61616"
      - "8161:8161"

  tasks-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - tasks-mysql-data:/var/lib/mysql
      - "../config/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  task-eureka:
    image: francescofiora-task-eureka
    environment:
      - "EUREKA_SERVER=task-eureka"
    ports:
      - "8761:8761"

  task-prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - "./prometheus/:/etc/prometheus/"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"      
    ports:
      - "9090:9090"
    depends_on:
      - task-eureka

  tasks-api:
    image: francescofiora-task-api
    environment:
      - "SPRING_PROFILES_ACTIVE=Logging"
      - "MONGODB_URI=mongodb://root:secret@tasks-mongodb:27017"
      - "BROKER_URL=tcp://tasks-activemq:61616"
      - "EUREKA_URI=http://user:password@task-eureka:8761/eureka"
    ports:
      - '8081:8081'
    depends_on:
      - tasks-mongodb
      - tasks-activemq
      - task-eureka

  task-executor:
    image: francescofiora-task-executor
    environment:
      - "DATASOURCE_URL=jdbc:mysql://tasks-mysql:3306/tasks"
      - "BROKER_URL=tcp://tasks-activemq:61616"
      - "EUREKA_URI=http://user:password@task-eureka:8761/eureka"
    ports:
      - '8082:8082'
    depends_on:
      - tasks-mysql
      - tasks-activemq
      - task-eureka

volumes:
  tasks-mysql-data:
  tasks-mongodb-data:
