SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `tasks` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `tasks`;

CREATE USER 'japp'@'%' IDENTIFIED BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE ON `tasks`.* TO 'japp'@'%';

CREATE USER 'jadmin'@'%' IDENTIFIED BY 'moresecret';
GRANT ALL PRIVILEGES ON `tasks`.* TO 'jadmin'@'%';
FLUSH PRIVILEGES;

COMMIT;
