version: '3'
services:

  tasks-mongodb:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'

  tasks-activemq:
    image: artemis-debian
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
      EXTRA_ARGS: "--http-host tasks-activemq --relax-jolokia"
    ports:
      - "61616:61616"
      - "8161:8161"

  tasks-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
   
  tasks-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      - PMA_HOST=tasks-mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"

  tasks-mongoclient:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL="mongodb://root:secret@tasks-mongodb:27017"
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - "8085:8081"

  tasks-sonarqube:
    image: sonarqube:8.9.7-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
